/**
 * Downloads the web fonts into public/fonts and writes fonts.css.
 *
 *   bun scripts/fetch-fonts.ts
 *
 * They are self-hosted so the app does not send every founder's IP address to
 * Google on page load. Latin and latin-ext subsets only — the cohort writes
 * Finnish and English, and the cyrillic/greek/vietnamese faces tripled the
 * download for nothing.
 *
 * Note: Google serves *static* instances for this request, not variable fonts,
 * so the `font-variation-settings: "opsz" ...` declarations scattered through
 * the UI have never had any effect. That was equally true when the fonts came
 * from the CDN; self-hosting neither caused nor fixed it.
 */
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120 Safari/537.36";

const SOURCE =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;900" +
  "&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;0,8..60,700;0,8..60,900;1,8..60,400;1,8..60,500" +
  "&display=swap";

const css = await (await fetch(SOURCE, { headers: { "User-Agent": UA } })).text();
const blocks = css.split("/*").slice(1).map((b) => "/*" + b);
const wanted = blocks.filter((b) => /^\/\* latin(-ext)? \*\//.test(b.trim()));

let out = "";
let count = 0;
for (const block of wanted) {
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
  if (!url) continue;
  const family = block.match(/font-family: '([^']+)'/)![1]!.replace(/\s+/g, "");
  const weight = (block.match(/font-weight: ([^;]+);/)?.[1] ?? "400").replace(/\s+/g, "-");
  const style = block.match(/font-style: (\w+)/)?.[1] ?? "normal";
  const subset = block.match(/^\/\* (latin(?:-ext)?) \*\//)![1];
  const name = `${family}-${style}-${weight}-${subset}.woff2`.toLowerCase();

  await Bun.write(`public/fonts/${name}`, await (await fetch(url[1]!, { headers: { "User-Agent": UA } })).arrayBuffer());
  out += block.replace(url[1]!, `/fonts/${name}`).trimEnd() + "\n";
  count++;
}

const header = [
  "/*",
  " * Generated by scripts/fetch-fonts.ts — do not edit by hand.",
  " *",
  " * Self-hosted so the app does not hand every founder's IP address to a",
  " * third party on page load. These are students' private reflections on an",
  " * EU-hosted service. Latin and latin-ext subsets only.",
  " */",
  "",
].join("\n");

await Bun.write("public/fonts/fonts.css", header + out);
console.log(`Wrote ${count} font files and public/fonts/fonts.css`);
